#!/bin/bash

# Configuration
BUCKET_NAME="snapsentinel-images-dev"
TABLE_NAME="analysis_results-dev"
REGION="us-east-1"
IMAGE_FILE="image.png"
IMAGE_ID="test-sh-$(date +%s).png"

# Ensure image exists
if [ ! -f "$IMAGE_FILE" ]; then
    echo "Downloading test image..."
    curl -o "$IMAGE_FILE" https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg
fi

echo "Uploading $IMAGE_ID to $BUCKET_NAME..."
aws s3 cp "$IMAGE_FILE" "s3://$BUCKET_NAME/$IMAGE_ID"

echo "Upload complete. Waiting for analysis (10s)..."
sleep 10

echo "Polling DynamoDB for image_id: $IMAGE_ID..."

# Query DynamoDB
# We need to scan or query. Since we know the PK (image_id), we can use get-item if we know the SK (timestamp).
# But we don't know the exact timestamp generated by the Lambda.
# So we should Query using the Partition Key only? No, Query requires PK.
# But if we don't know the Sort Key, we can use Query with KeyConditionExpression if we only specify PK?
# Wait, if table has Sort Key, GetItem needs both. Query can work with just PK.

RESULT=$(aws dynamodb query \
    --table-name "$TABLE_NAME" \
    --key-condition-expression "image_id = :id" \
    --expression-attribute-values "{ \":id\": {\"S\": \"$IMAGE_ID\"} }" \
    --region "$REGION" \
    --output json)

COUNT=$(echo "$RESULT" | grep -o '"Count": [0-9]*' | awk '{print $2}')

if [ "$COUNT" -gt 0 ]; then
    echo "Test Passed: Record found in DynamoDB!"
    echo "$RESULT"
else
    echo "Test Failed: Record not found in DynamoDB."
    exit 1
fi
